services:
  qcraft:
    build: .
    container_name: qcraft
    restart: unless-stopped
    ports:
      - "9898:5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Zurich
